name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Setup FVM
        run: dart pub global activate fvm

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Analyze
        run: fvm flutter analyze --fatal-infos --fatal-warnings .
      
      - name: Test
        run: fvm flutter test --no-pub --coverage

      - name: Install dependencies for example
        run: fvm flutter pub get
        working-directory: example

      - name: Analyze example
        run: fvm flutter analyze --fatal-infos --fatal-warnings example
        working-directory: example

      - name: Test example
        run: fvm flutter test --no-pub --coverage example
        working-directory: example
